In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/sentiment-prediction-on-movie-reviews/movies.csv
/kaggle/input/sentiment-prediction-on-movie-reviews/sample.csv
/kaggle/input/sentiment-prediction-on-movie-reviews/train.csv
/kaggle/input/sentiment-prediction-on-movie-reviews/test.csv

In [2]:
sample_data = pd.read_csv("/kaggle/input/sentiment-prediction-on-movie-reviews/sample.csv")
movies_data = pd.read_csv("/kaggle/input/sentiment-prediction-on-movie-reviews/movies.csv")
train_data = pd.read_csv("/kaggle/input/sentiment-prediction-on-movie-reviews/train.csv")
test_data = pd.read_csv("/kaggle/input/sentiment-prediction-on-movie-reviews/test.csv")

In [3]:
print(sample_data.shape, "\n")
print(sample_data.isnull().sum(),"\n")
print(sample_data.info(),"\n")
print(sample_data.head(),"\n")
sample_data.describe()

(55315, 2)

id           0
sentiment    0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55315 entries, 0 to 55314
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         55315 non-null  int64
 1   sentiment  55315 non-null  object
dtypes: int64(1), object(1)
memory usage: 864.4+ KB
None

   id sentiment
0   0  NEGATIVE
1   1  NEGATIVE
2   2  NEGATIVE
3   3  NEGATIVE
4   4  NEGATIVE

                 id
count  55315.000000
mean   27657.000000
std    15968.209407
min        0.000000
25%    13828.500000
50%    27657.000000
75%    41485.500000
max    55314.000000

In [4]:
print(movies_data.shape, "\n")
print(movies_data.isnull().sum(),"\n")
print(movies_data.info(),"\n")
print(movies_data.head(),"\n")
movies_data.describe()

(143258, 14)

movieid                      0
title                        0
audienceScore            70010
rating                  129267
ratingContents          129267
releaseDateTheaters     112485
releaseDateStreaming     63838
runtimeMinutes           13827
genre                    11083
originalLanguage         13858
director                     0
boxOffice               128515
distributor             120253
soundType               127341
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 143258 entries, 0 to 143257
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   movieid               143258 non-null  object
 1   title                 143258 non-null  object
 2   audienceScore         73248 non-null   float64
 3   rating                13991 non-null   object
 4   ratingContents        13991 non-null   object
 5   releaseDateTheaters   30773 non-null   object
 6   releaseDateStreaming  79420 non-null   object
 7   runtimeMinutes        129431 non-null  float64
 8   genre                 132175 non-null  object
 9   originalLanguage      129400 non-null  object
 10  director              143258 non-null  object
 11  boxOffice             14743 non-null   object
 12  distributor           23005 non-null   object
 13  soundType             15917 non-null   object
dtypes: float64(2), object(12)
memory usage: 15.3+ MB
None

                                             movieid  \
0                  han_solo_heroic_myth_wonder_woman
1              voyage_tyler_durden_han_solo_stardust
2  norman_bates_ferris_bueller_hermione_granger_v...
3                           elegant_hermione_granger
4                             adventure_rocky_balboa

                                               title  audienceScore rating  \
0                  Han Solo Heroic Myth Wonder Woman           50.0    NaN
1              Voyage Tyler Durden Han Solo Stardust            NaN    NaN
2  Norman Bates Ferris Bueller Hermione Granger V...           43.0    NaN
3                           Elegant Hermione Granger           60.0    NaN
4                             Adventure Rocky Balboa           70.0    NaN

  ratingContents releaseDateTheaters releaseDateStreaming  runtimeMinutes  \
0            NaN                 NaN           2018-08-25            75.0
1            NaN                 NaN           2020-02-11           114.0
2            NaN                 NaN                  NaN           120.0
3            NaN                 NaN           2020-10-23            90.0
4            NaN                 NaN           2017-03-27            80.0

                           genre originalLanguage        director boxOffice  \
0         Comedy, Horror, Sci-fi          English  Claude Nicolet       NaN
1                          Drama          English    Nathan Haack       NaN
2                          Drama           Korean   Theresa Smith       NaN
3     Action, Mystery & thriller          English    Donald Lewis       NaN
4  Fantasy, Adventure, Animation          English    Howard Simms       NaN

  distributor soundType
0         NaN       NaN
1         NaN       NaN
2         NaN       NaN
3         NaN       NaN
4         NaN       NaN

       audienceScore  runtimeMinutes
count   73248.000000   129431.000000
mean       55.674967       93.708578
std        24.553648       28.129175
min         0.000000        1.000000
25%        37.000000       84.000000
50%        57.000000       92.000000
75%        76.000000      103.000000
max       100.000000     2700.000000

In [5]:
print(train_data.shape, "\n")
print(train_data.isnull().sum(),"\n")
print(train_data.info(),"\n")
print(train_data.head(),"\n")
train_data.describe()

(162758, 5)

movieid                  0
reviewerName             0
isFrequentReviewer       0
reviewText            6447
sentiment                0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 162758 entries, 0 to 162757
Data columns (total 5 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   movieid             162758 non-null  object
 1   reviewerName        162758 non-null  object
 2   isFrequentReviewer  162758 non-null  bool
 3   reviewText          156311 non-null  object
 4   sentiment           162758 non-null  object
dtypes: bool(1), object(4)
memory usage: 5.1+ MB
None

                                             movieid         reviewerName  \
0                                   marvelous_pirate       Benjamin Henry
1          tony_montana_frodo_baggins_v_rocky_balboa        Felicia Lopez
2  darth_vader_katniss_everdeen_sorcerer_donnie_d...  Mr. Charles Burgess
3                                 lara_croft_glimmer         Ryan Barrett
4  jason_bourne_surreal_the_terminator_indiana_jones     Alexander Glover

   isFrequentReviewer                                         reviewText  \
0               False  Henry Selick’s first movie since 2009’s Corali...
1               False  With a cast that reads like the Vogue Oscar pa...
2                True  Creed II does not give us anything but another...
3               False  I know what you're thinking, but this is no Li...
4               False  Director Fernando Meirelles tells the story wi...

  sentiment
0  POSITIVE
1  NEGATIVE
2  POSITIVE
3  POSITIVE
4  POSITIVE

,movieid,reviewerName,isFrequentReviewer,reviewText,sentiment
count,162758,162758,162758,156311,162758
unique,16812,4482,2,155071,2
top,escape_the_terminator_tyler_durden_astonish,Sherri Morrison,False,Parental Content Review,POSITIVE
freq,708,962,113189,29,108761

In [6]:
print(test_data.shape, "\n")
print(test_data.isnull().sum(),"\n")
print(test_data.info(),"\n")
print(test_data.head(),"\n")
test_data.describe()

(55315, 4)

movieid            0
reviewerName       0
isTopCritic        0
reviewText      2510
dtype: int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55315 entries, 0 to 55314
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   movieid       55315 non-null  object
 1   reviewerName  55315 non-null  object
 2   isTopCritic   55315 non-null  bool
 3   reviewText    52805 non-null  object
dtypes: bool(1), object(3)
memory usage: 1.3+ MB
None

                               movieid     reviewerName  isTopCritic  \
0            legend_marty_mcfly_oracle         John Kim        False
1  terminator_katniss_everdeen_glimmer     Brian Chaney        False
2          james_bond_labyrinth_gollum  Danielle Parker        False
3            v_quest_han_solo_wondrous    Brittany Lane        False
4        enigma_hulk_surreal_starlight    Justin Willis        False

                                          reviewText
0  Green slowly cranks up the dread with style an...
1  Philip Noyce's direction is elegant and unforc...
2  It wouldn't do to say what path Maria ultimate...
3  Pig is not exactly the arthouse John Wick that...
4  An imaginative no-budget musical of sorts abou...

,movieid,reviewerName,isTopCritic,reviewText
count,55315,55315,55315,52805
unique,16786,4495,2,52686
top,escape_the_terminator_tyler_durden_astonish,Sherri Morrison,False,Parental Content Review
freq,230,428,38428,12

In [7]:
#Merging movies data into train data
merged_data = train_data.merge(movies_data)

print(merged_data.shape, "\n")
merged_data

(525277, 18)

,movieid,reviewerName,isFrequentReviewer,reviewText,sentiment,title,audienceScore,rating,ratingContents,releaseDateTheaters,releaseDateStreaming,runtimeMinutes,genre,originalLanguage,director,boxOffice,distributor,soundType
0,marvelous_pirate,Benjamin Henry,False,Henry Selick’s first movie since 2009’s Corali...,POSITIVE,Marvelous Pirate,65.0,PG-13,"['Violence', 'Brief Strong Language', 'Substan...",2022-10-21,2022-10-28,105.0,"Comedy, Animation, Adventure, Fantasy",English,Bennie Basso,NaN,Netflix,NaN
1,marvelous_pirate,Sharon Foster,False,&#91;T&#93;he haphazard way this story is asse...,NEGATIVE,Marvelous Pirate,65.0,PG-13,"['Violence', 'Brief Strong Language', 'Substan...",2022-10-21,2022-10-28,105.0,"Comedy, Animation, Adventure, Fantasy",English,Bennie Basso,NaN,Netflix,NaN
2,marvelous_pirate,Melinda Dunn,False,The stop-motion artistry of Wendell &amp; Wild...,POSITIVE,Marvelous Pirate,65.0,PG-13,"['Violence', 'Brief Strong Language', 'Substan...",2022-10-21,2022-10-28,105.0,"Comedy, Animation, Adventure, Fantasy",English,Bennie Basso,NaN,Netflix,NaN
3,marvelous_pirate,Mr. Wayne Smith,False,Wendell &amp; Wild is narratively overstuffed ...,NEGATIVE,Marvelous Pirate,65.0,PG-13,"['Violence', 'Brief Strong Language', 'Substan...",2022-10-21,2022-10-28,105.0,"Comedy, Animation, Adventure, Fantasy",English,Bennie Basso,NaN,Netflix,NaN
4,marvelous_pirate,Connor Nelson,False,For being about the Netherworlds&#44; it&#8217...,POSITIVE,Marvelous Pirate,65.0,PG-13,"['Violence', 'Brief Strong Language', 'Substan...",2022-10-21,2022-10-28,105.0,"Comedy, Animation, Adventure, Fantasy",English,Bennie Basso,NaN,Netflix,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525272,frodo_baggins_norman_bates_ellen_ripley_astonish,Janice Pearson,False,The broad shape of the ending is predictable; ...,NEGATIVE,Frodo Baggins Norman Bates Ellen Ripley Astonish,81.0,NaN,NaN,NaN,2019-03-19,111.0,"Crime, Drama",Filipino,Sara Maggard,NaN,NaN,NaN
525273,elegant_starlight_labyrinth_katniss_everdeen,Frank Farrell,False,A formula designed for adolescent and young ad...,POSITIVE,Elegant Starlight Labyrinth Katniss Everdeen,75.0,NaN,NaN,2018-04-13,2018-09-18,93.0,"Horror, Mystery & thriller",Korean,Frances Gagne,$111.2K,Well Go USA,NaN
525274,don_vito_corleone_neo_hannibal_lecter,Juan Taylor,False,"All these years, I've kept a soft spot in my h...",NEGATIVE,Don Vito Corleone Neo Hannibal Lecter,55.0,NaN,NaN,1987-02-20,2009-04-14,96.0,Comedy,English,Claudia Bernhard,$799.4K,NaN,NaN
525275,dorothy_gale_luke_skywalker_luke_skywalker,Robert Cardenas,False,Powerful documentary about the struggle of Wes...,POSITIVE,Dorothy Gale Luke Skywalker Luke Skywalker,75.0,NaN,NaN,2008-02-29,2009-07-14,89.0,Documentary,English,James Fanney,NaN,NaN,NaN
525276,forrest_gump_fantasy_epic,Daniel Pacheco,True,Rock's wildest years - both the man and the mu...,POSITIVE,Forrest Gump Fantasy Epic,45.0,NaN,NaN,2017-04-07,2017-04-07,95.0,"Documentary, Music",English,Tawanda Ballard,$14.0K,Magnolia Pictures,NaN

In [8]:
print(merged_data.shape, "\n\n")
print(merged_data.isnull().sum(),"\n\n")
merged_data.info()

(525277, 18)


movieid                      0
reviewerName                 0
isFrequentReviewer           0
reviewText               23817
sentiment                    0
title                        0
audienceScore           300829
rating                  390791
ratingContents          390791
releaseDateTheaters     342951
releaseDateStreaming    275844
runtimeMinutes          222688
genre                   217333
originalLanguage        220455
director                     0
boxOffice               380216
distributor             355592
soundType               415919
dtype: int64


<class 'pandas.core.frame.DataFrame'>
Int64Index: 525277 entries, 0 to 525276
Data columns (total 18 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   movieid               525277 non-null  object
 1   reviewerName          525277 non-null  object
 2   isFrequentReviewer    525277 non-null  bool
 3   reviewText            501460 non-null  object
 4   sentiment             525277 non-null  object
 5   title                 525277 non-null  object
 6   audienceScore         224448 non-null  float64
 7   rating                134486 non-null  object
 8   ratingContents        134486 non-null  object
 9   releaseDateTheaters   182326 non-null  object
 10  releaseDateStreaming  249433 non-null  object
 11  runtimeMinutes        302589 non-null  float64
 12  genre                 307944 non-null  object
 13  originalLanguage      304822 non-null  object
 14  director              525277 non-null  object
 15  boxOffice             145061 non-null  object
 16  distributor           169685 non-null  object
 17  soundType             109358 non-null  object
dtypes: bool(1), float64(2), object(15)
memory usage: 72.6+ MB

In [9]:
from sklearn.model_selection import train_test_split

#Randomly Splitting for unbiased evaluation
train_size = 0.8
X = train_data.drop(columns= ['sentiment']).copy()
y = train_data['sentiment']

X_train, X_rem, y_train, y_rem = train_test_split(X, y, train_size=train_size)

#now i want to divide remaining data into 50-50 for valid and test size
test_size = 0.5
X_valid, X_test, y_valid, y_test = train_test_split(X_rem,y_rem, test_size=test_size)

print(X_train.shape), print(y_train.shape)
print(X_valid.shape), print(y_valid.shape)
print(X_test.shape), print(y_test.shape)

(130206, 4)
(130206,)
(16276, 4)
(16276,)
(16276, 4)
(16276,)

(None, None)

In [10]:
#Data preprocessing
#Converting object data into numeric values

from sklearn.feature_extraction.text import TfidfVectorizer
# from sklearn.feature_extraction.text import CountVectorizer
# from sklearn.pipeline import Pipeline

#To impute missing values in categorical as well as numerical
from sklearn.impute import SimpleImputer

X_train = train_data.drop(columns=['sentiment']).copy()
y_train = train_data['sentiment']

X_test = test_data

#Filling null values with NaN value to make that easily fillable
X_train = X_train.fillna(np.nan)
X_test = X_test.fillna(np.nan)

#Getting all the list of columns in train and test data
X_train_cols = list(X_train.keys())
X_test_cols = list(X_test.keys())

#Getting all the types of train columns
X_train_types = dict(X_train.dtypes)

# print(X_train_cols)
# print(X_train_types)

#Filtering categorical and numerical columns
cat_dict = []
num_dict = []
bool_dict = []
for i,j in X_train_types.items():
    if j == "object":
        cat_dict.append(i)
    elif j == "float":
        num_dict.append(i)
    elif j == "bool":
        bool_dict.append(i)

#Imputing missing values
si1= SimpleImputer(missing_values=np.nan, strategy='most_frequent')
si2= SimpleImputer(missing_values=np.nan, strategy='most_frequent')

X_train1 = si1.fit_transform(X_train)
X_test1 = si2.fit_transform(X_test)

# print(X_train1)
# print(X_test1)

X_train = pd.DataFrame(X_train1, columns = X_train_cols)
X_test = pd.DataFrame(X_test1, columns = X_test_cols)

# print(X_train)    
# print(cat_dict) ['movieid', 'reviewerName', 'reviewText', 'title', 'rating', 
#'ratingContents', 'releaseDateTheaters', 'releaseDateStreaming', 'genre', 'originalLanguage',
#'director', 'boxOffice', 'distributor', 'soundType']
# print(num_dict) ['audienceScore', 'runtimeMinutes']

vectorizer = TfidfVectorizer(lowercase=True, max_features=40000)

X_train_reviewText = vectorizer.fit_transform(X_train['reviewText'])
X_test_reviewText = vectorizer.fit_transform(X_test['reviewText'])    

print(X_train_reviewText.shape)
print(X_test_reviewText.shape)

(162758, 40000)
(55315, 40000)

In [11]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, StratifiedKFold

logit = LogisticRegression(C=5e1, solver='newton-cg', multi_class='multinomial', 
                           random_state=17, n_jobs=4)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=17)

cv_results = cross_val_score(logit, X_train_reviewText, y_train, 
                             cv=skf, scoring='f1_micro')
cv_results, cv_results.mean()

(array([0.77512902, 0.77841607, 0.77558983, 0.77834782, 0.77742619]),
 0.7769817877489319)

In [12]:
logit.fit(X_train_reviewText, y_train)

test_preds = logit.predict(X_test_reviewText)
pred = pd.DataFrame(test_preds, columns=['sentiment'])
pred.index.name = 'id'
pred.to_csv('submission.csv')